project:
  type: website
  output-dir: _site

website:
  title: "rxsim gallery"
  navbar:
    right:
      - icon: github
        href: https://github.com/Boehringer-Ingelheim/rxsim
      - text: "rxsim docs"
        href: https://boehringer-ingelheim.github.io/rxsim

format:
  html:
    theme: cosmo
    css: assets/css/custom.css
    toc: true
    code-tools: true
